packages:
  - packages/logger
  - packages/player
  - packages/pages
  - packages/platform
  - packages/platform-playground
  - packages/desktop
  - packages/desktop-v3
  - packages/desktop-tauri
  - packages/docs
  - packages/mcp-debug